[package]
name = "test_cuda"
version = "0.1.0"
edition = "2024"

[dependencies]
cudarc = {version = "0.16.3", features = ["cuda-12080"]}


# Graphics stuff
env_logger = "0.11.8"
error-iter = "0.4.1"
pixels = "0.15.0"
log = "0.4.27"
winit = "0.29.15"
winit_input_helper = "0.15.3"